### PR TITLE
setting up rultor config

### PR DESCRIPTION
**Pull request by mpollmeier**

### CODE REVIEW

**Comment by mpollmeier** [comment]
@rultor release

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-test`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-test`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-test2`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-test3`

**Comment by velo** [comment]
there is also @rultor  merge =D

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-test3`

**Comment by mpollmeier** [comment]
@velo does `merge` really help us? travis is running automatically anyway, so what else does it add?

**Comment by velo** [comment]
Kinda...

Them we can be sure merges went fine

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by velo** [comment]
Add -B to maven to make it less verbose

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
fyi: related discussion on sonatype oss re the signing and uploading of artifacts - I'm still in the phase of trying to understand how their security concept works. 

https://issues.sonatype.org/browse/OSSRH-25016

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
hmm, looks like i've got the same issue as https://github.com/yegor256/rultor/issues/915
trying to use their parent pom...

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@rultor release, tag=`rultor-tests`

**Comment by mpollmeier** [comment]
@velo looking good, just awaiting for rultor to become a collaborator (they need to accept manually) and we should be good to go. not sure how it handles proper releases, I guess we just need to drop '-SNAPSHOT'...

**Comment by mpollmeier** [comment]
Ok I spent enough time on this... I'm giving up. I'll keep the current state in branch `rultor` and revert some commits in master to get us back into a green state.
Here's what I tried and what went wrong, in case someone else wants to try fix rultor integration: 

With all the described changes to the pom as described in http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html WITHOUT inheriting from some parent pom, rultor did not find the provided gpg keys. I basically had the same issue as in https://github.com/yegor256/rultor/issues/915

As suggested in https://github.com/yegor256/rultor/issues/915 I then used jcapi-parent as the parent pom as it configures a few more things that rultor needs. Then it did find the gpg keys, but as it configures every plugin under the sun I then ran into loads of problems with travis (e.g. i had to unset some java compiler flags, reconfigure the maven failsafe forkCount etc.) and now I'm down to a NullPointerException that I have no idea how to fix.

**Pull request merged**
