### PR TITLE
Removing invalid javadoc tags

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by velo** [comment]
Fair reason for failure...
https://travis-ci.org/mpollmeier/orientdb-gremlin#L773

Suggestions?

**Comment by mpollmeier** [comment]
Why did you add the 'release' profile? If it's needed we could probably disable the gpg step in the pipeline...

Independently of that: Currently only I can sign those artifacts (and therefor publish). I'm happy to make you able to sign and publish as well, but I'm not sure if we can (or should) get travis to do be able to publish.

**Comment by velo** [comment]
I only wanted to package the javadocs... I guess I will need to move it outside the profile.  What do you think?

**Comment by mpollmeier** [comment]
Can you create a separate profile to package up the javadocs? Or make javadoc generation part of the 'travis' profile?

**Comment by mpollmeier** [comment]
just released 3.1.1-incubating.0

**Pull request merged**
