### PR TITLE
Vertex test

### PR DESCRIPTION
**Pull request by velo**
This is meant to be merged/reviewed after #10 

Tests run: 776, Failures: 33, Errors: 178, Skipped: 261

### CODE REVIEW

**Comment by mpollmeier** [comment]
thanks mate, much appreciated. I had to fix one test on the scala side though as `V` doesn't count as a label any more - which makes sense. I just published 3.0.0.M4.

**Comment by velo** [comment]
ops, my bad.... can we setup a travis CI for the project?

**Comment by mpollmeier** [comment]
just made you a collaborator, and I've enabled travis for this project. can you configure the .travis.yml configuration etc.?

**Comment by mpollmeier** [comment]
https://travis-ci.org/mpollmeier/orientdb-gremlin/

**Comment by velo** [comment]
absolutelly

**Pull request merged**
