### PR TITLE
Testing 2.2.0-beta

### PR DESCRIPTION
**Pull request by velo**
Out of curiosity, how far are we from 2.2.0-beta?

### CODE REVIEW

**Comment by velo** [comment]
Problem...
ODatabaseFactory is gone for 2.2... how shall we handle that?
https://github.com/orientechnologies/orientdb/commit/e0dac718d5035a9d1747bfddad78ca7e091cb78f

**Comment by mpollmeier** [comment]
looks like the new way is just 
```
new ODatabaseDocumentTx("...");
```

**Comment by mpollmeier** [comment]
i really like this change btw: https://github.com/orientechnologies/orientdb/issues/4818

**Comment by velo** [comment]
True, but that does break compatibility between 2.1.* and 2.2.*

**Comment by mpollmeier** [comment]
True, but being such a small project we still have the luxury of being able to make breaking changes. People who are on orient 2.1 can continue to use the current version, and if they want to use the latest version of the driver they probably have to upgrade Orient as well. 
If we had a million users we obviously couldn't do that :)

**Comment by velo** [comment]
True...

**Pull request closed without merging**
